
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gustavo.msanchez
 */
public class Equacao extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public Equacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        x2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        b = new javax.swing.JTextField();
        textx1 = new javax.swing.JLabel();
        textx2 = new javax.swing.JLabel();
        textdelta = new javax.swing.JLabel();
        delta = new javax.swing.JTextField();
        x1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        sair = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Equação de 2 grau");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("= 0");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 0, 110, 70);

        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(260, 20, 50, 40);

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(20, 20, 50, 40);

        x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x2ActionPerformed(evt);
            }
        });
        getContentPane().add(x2);
        x2.setBounds(200, 250, 50, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("x +");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 0, 110, 70);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("x² +");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 0, 70, 70);

        calcular.setBackground(new java.awt.Color(0, 255, 0));
        calcular.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular);
        calcular.setBounds(40, 90, 160, 40);

        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(150, 20, 50, 40);

        textx1.setBackground(new java.awt.Color(204, 255, 204));
        textx1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textx1.setText("O valor de x1 é :");
        getContentPane().add(textx1);
        textx1.setBounds(40, 200, 160, 40);

        textx2.setBackground(new java.awt.Color(204, 255, 204));
        textx2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textx2.setText("O valor de x2 é :");
        getContentPane().add(textx2);
        textx2.setBounds(40, 250, 170, 40);

        textdelta.setBackground(new java.awt.Color(204, 255, 204));
        textdelta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textdelta.setText("O valor de delta é :");
        getContentPane().add(textdelta);
        textdelta.setBounds(40, 150, 160, 40);

        delta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deltaActionPerformed(evt);
            }
        });
        getContentPane().add(delta);
        delta.setBounds(200, 150, 50, 40);

        x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1ActionPerformed(evt);
            }
        });
        getContentPane().add(x1);
        x1.setBounds(200, 200, 50, 40);
        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(410, 0, 0, 400);

        sair.setBackground(new java.awt.Color(255, 51, 51));
        sair.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(260, 310, 110, 40);

        Limpar.setBackground(new java.awt.Color(102, 102, 255));
        Limpar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        getContentPane().add(Limpar);
        Limpar.setBounds(40, 310, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ilustracao-da-lousa-verde_69037-26.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-30, 0, 450, 400);

        setSize(new java.awt.Dimension(425, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x2ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void deltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deltaActionPerformed

    private void x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1ActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        int va, vb, vc, vdelta;
        double vx1, vx2;
        va = Integer.parseInt(a.getText());
        vb = Integer.parseInt(b.getText());
        vc = Integer.parseInt(c.getText());
        vdelta = vb * vb - 4 * va * vc;
        delta.setText(String.valueOf(vdelta));
        
        if(vdelta < 0){
            JOptionPane.showMessageDialog(null, "Não há valor de X possivel");
        }else if (vdelta==0){
            vx1 = (-vb + Math.sqrt(vdelta)) /2 * va;
            x1.setText(String.valueOf(vx1));
        }else {
            vx1 = (-vb + Math.sqrt(vdelta)) /2 * va;
            vx2 = (-vb - Math.sqrt(vdelta)) /2 * va;
            x1.setText(String.valueOf(vx1));
            x2.setText(String.valueOf(vx2));
        }
    }//GEN-LAST:event_calcularActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
       a.setText("");
       b.setText("");
       c.setText("");
       delta.setText("");
       x1.setText("");
       x2.setText("");
    }//GEN-LAST:event_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpar;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JButton calcular;
    private javax.swing.JTextField delta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sair;
    private javax.swing.JLabel textdelta;
    private javax.swing.JLabel textx1;
    private javax.swing.JLabel textx2;
    private javax.swing.JTextField x1;
    private javax.swing.JTextField x2;
    // End of variables declaration//GEN-END:variables
}
